name: angular-sportsstore-ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: build
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup Node ${{ env.NODE_VERSION }}
        env:
          NODE_VERSION: '12.x'
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - run: npm run test
      - run: sudo apt-get update && sudo apt-get install google-chrome-stable
      - run: cd cert && ./generate.sh
      - run: npm run e2e-ci
      - name: Publish build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
      - name: Publish code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage
